# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SongName', models.CharField(max_length=100)),
                ('Singer', models.CharField(max_length=100)),
                ('Lyric', models.CharField(max_length=10000)),
            ],
        ),
    ]
